linux: cve-exclusions: Add --always to git-describe
Otherwise https://git.kernel.org/pub/scm/linux/security/vulns.git cannot be
used:

subprocess.CalledProcessError: Command '('git', 'describe', '--tags', 'HEAD')' returned non-zero exit status 128.

Original error from git:

fatal: No names found, cannot describe anything.

The change will at least produce an abbreviated SHA1 hash as {data_version}.

Fixes: 5e66e2b79fae ("linux/generate-cve-exclusions: show the name and version of the data source")
Signed-off-by: Alexander Sverdlin <alexander.sverdlin@siemens.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>