Python: Add missing dependency "textutils" to "io" package
Modify the include file and script to generate a missing RDEPENDS.

Install python on target with python-io. Import ssl:

Python 2.7.3 (default, Feb  9 2013, 16:04:35)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ssl.py", line 58, in <module>
ImportError: No module named textwrap

Installing python-textutils solves the issue.

Signed-off-by: MiLo <milo-software@users.sourceforge.net>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>