gn: fix build with GCC 16 on musl
Add missing <cstdint> include in src/gn/pool.h for int64_t.

Fixes:
| ../sources/gn-0+git/src/gn/pool.h:26:3: error: 'int64_t' does not name a type

Upstream-Status: Submitted [https://gn-review.googlesource.com/c/gn/+/22740]

Signed-off-by: Hemanth Kumar M D <Hemanth.KumarMD@windriver.com>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>