python3-setuptools: add missing rdepends for python3-pkg-resources
Add missing rdepends for python3-pkg-resources to fix below error:
 # python3
 [snip]
 import pkg_resources
 [snip]
 ModuleNotFoundError: No module named 'plistlib'
 ModuleNotFoundError: No module named 'email'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>