lttng-tools: fixes a wrong header issue
This fixes a following compiling issue:
| agent.c:33:19: fatal error: error.h: No such file or directory
|  #include "error.h"

it's back-ported from lttng-tools upstream, we need it in SRC_URI
since 2.8 is still the latest release.

Signed-off-by: Ming Liu <peter.x.liu@external.atlascopco.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>