yocto-check-layer: Add messages in test_readme assertions
Assertions in test_readme does not provide context message when they
fail. Which leads to errors like:

  File "/media/workspace/yocto_master/openembedded-core/scripts/lib/checklayer/cases/common.py", line 41, in test_readme
    self.assertTrue(email_regex.match(data))
    AssertionError: None is not true

This patch adds context messages to the assertions to help identify the
issue when they fail.

Signed-off-by: Ricardo Ungerer <ungerer.ricardo@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>