glibc: unify wordsize.h between arm and aarch64
There is a redundant change in
0016-wordsize.h-Unify-the-header-between-arm-and-aarch64.patch that
causes wordsize.h to be different in arm and aarch64. This causes the
build error when enable multilib:

Error: Transaction test error:
  file /usr/include/bits/wordsize.h conflicts between attempted installs of lib32-libc6-dev-2.37-r0.armv7vet2hf_vfp and libc6-dev-2.37-r0.cortexa57

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>