weston: Add a knob to control simple clients
Some graphics driver implementations ( e.g sgx ) do not yet support APIs from mesa
21.x, and some portions of weston simple clients depend on these APIs,
therefore introduce a way to specify all or a selection fo clients to
build

Fixes

clients/weston-simple-dmabuf-feedback.p/simple-dmabuf-
feedback.c.o: in function `create_dmabuf_buffer':
| simple-dmabuf-feedback.c:(.text+0x1076): undefined reference to `gbm_bo_get_fd_for_plane'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>