systemtap: disable libvirt
libvirt is automatically linked to if present, this undetermined
dependency may cause build errors like:

  ../lib/libvirt.so: undefined reference to `libssh2_channel_open_ex'
  ../lib/libvirt.so: undefined reference to `libssh2_session_hostkey'
  ...

Both libvirt and libssh2 are not oe-core recipes for now, just disable
libvirt to fix this issue.

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>