ncurses: upgrade 6.5 -> 6.6
1. License-Update: copyright years updated

2. Fix installed-vs-shipped QA error
...
ERROR: ncurses-6.6-r0 do_package: QA Issue: ncurses: Files/directories were installed but not shipped in any package:
  /usr/lib
ncurses: 1 installed and not shipped files. [installed-vs-shipped]
...

Due to commit [1], upstream hardcoded `lib` to create symlink
...
 ** sym-linked tmp/work/x86-64-v3-oe-linux/ncurses/6.6/image/usr/lib/terminfo for compatibility
...

Apply a local patch to not create symlink terminfo under image/usr/lib,
and clean up symlink remove operation in recipe

3. Delete backport patch
- CVE-2025-6141.patch

4. Announcing ncurses 6.6:
  https://lists.gnu.org/archive/html/info-gnu/2025-12/msg00010.html

[1] https://github.com/ThomasDickey/ncurses-snapshots/commit/a60b584d93ab59e1df0bc9661b7

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>