libdnf: Fix arm arch mapping issues for qemuarmv5
qemuarmv5 currently fails with:

$ dnf --help
Error: Incorrect or unknown "arch": armv5hl

Fix this by removing the code in libdnf which is trying to be too
clever, we don't need this mappings given the way OE configures rpm.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>