qemu.inc: Remove mesa-xlib as PREFERRED_PROVIDER
The xserver-xorg uses and depends on mesa-dri, so we should
use the default PREFERRED_PROVIDER of libgl as mesa-dri.

This resolves the following:
ERROR: Multiple .bb files are due to be built which each provide virtual/libgl (/intel/poky/distro/meta/recipes-graphics/mesa/mesa-dri_7.11.bb /intel/poky/distro/meta/recipes-graphics/mesa/mesa-xlib_7.11.bb).
 This usually means one provides something the other doesn't and should.

Signed-off-by: Saul Wold <sgw@linux.intel.com>