systemtap: fix do_compile failed on fedora21
For dora, the systemtap-native do_compile failed on fedora21
...
| In file included from /usr/include/stdio.h:27:0,
|                  from tmp/work/x86_64-linux/systemtap-native/
2.3+gitAUTOINC+e58138572e-r0/git/staprun/staprun.h:18,
|                  from tmp/work/x86_64-linux/systemtap-native/
2.3+gitAUTOINC+e58138572e-r0/git/staprun/staprun.c:24:
| /usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and
_SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
|  # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use
_DEFAULT_SOURCE"
...

We backport a patch from 2.6 to fix this issue

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>