qemu: fix for virtfs configuration error in qemu 5.0.0
Add --enable-cap-ng as virtfs dependency in qemu configuration.
When using meta-virtualization layer, qemu requires virtfs,
but during do_configure stage below error message shows up:

  ERROR: VirtFS requires libcap-ng devel and libattr devel

Signed-off-by: Kamil Dziezyk <kamil.dziezyk@arm.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>