libx11: fix build error
libx11 build fails with this error:

fatal error: bits/long-double-64.h: No such file or directory
| compilation terminated.

This is due to the fact that "makekeys" should be compiled for the host
since it is executed at build time to generate ks_tables.h. Since we have
the X11 include files in the standard path of oe-core, we can remove the
X11_CFLAGS from Makefile.

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>