curl: fix build when proxy is not enabled in PACKAGECONFIG
Backport upstream patches to fix issues introduced by a backported CVE
patch. Fixes:

| ../../curl-7.75.0/lib/vtls/vtls.c: In function ‘Curl_ssl_addsessionid’:
| ../../curl-7.75.0/lib/vtls/vtls.c:508:14: error: ‘isProxy’ redeclared as different kind of symbol
|   508 |   const bool isProxy = FALSE;
|       |              ^~~~~~~
| ../../curl-7.75.0/lib/vtls/vtls.c:488:37: note: previous definition of ‘isProxy’ with type ‘_Bool’
|   488 |                                bool isProxy,
|       |                                     ^

Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>