npm: Convert to list-based commands for NpmEnvironment.run()
This only affects those who have bypassed npm being disabled in bitbake (post commit 355cd226)

This recent upstream bitbake commit:
https://git.openembedded.org/bitbake/commit/?id=2ee0a002cd50eec1a0743c9ced9e07e529c79ddf

broke npm install commands within the npm bitbake class since NpmEnvironment.run() expects a list
instead of a string. Update the remaining callers to pass list-based commands to avoid:

  AttributeError: 'str' object has no attribute 'append'

Signed-off-by: Eric Meyers <eric.meyers@arthrex.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>