python3-cryptography{-vectors}: upgrade 48.0.1 -> 49.0.0
Add:
TARGET_CFLAGS:append = "-I${STAGING_INCDIR}/python${PYTHON_BASEVERSION}"

to fix an error in do_compile:

warning: cryptography-cffi@0.49.0: .../release/build/cryptography-cffi-d4ad0316804194ce/out/_openssl.c:57:10:
         fatal error: Python.h: No such file or directory
warning: cryptography-cffi@0.49.0:    57 | #include <Python.h>
warning: cryptography-cffi@0.49.0:       |          ^~~~~~~~~~
warning: cryptography-cffi@0.49.0: compilation terminated.

Backwards incompatible subset of upstream release notes:

49.0.0 - 2026-06-12
* BACKWARDS INCOMPATIBLE: Support for x86_64 macOS has been removed. We
  now only publish arm64 wheels for macOS.
* BACKWARDS INCOMPATIBLE: Support for 32-bit Windows has been removed.
  Users should move to a 64-bit Python installation.
* BACKWARDS INCOMPATIBLE: Removed the deprecated PUBLIC_KEY_TYPES,
  PRIVATE_KEY_TYPES, CERTIFICATE_PRIVATE_KEY_TYPES,
  CERTIFICATE_ISSUER_PUBLIC_KEY_TYPES, and CERTIFICATE_PUBLIC_KEY_TYPES
  type aliases. Use PublicKeyTypes, PrivateKeyTypes,
  CertificateIssuerPrivateKeyTypes, CertificateIssuerPublicKeyTypes, and
  CertificatePublicKeyTypes instead. These were deprecated in version
  40.0.
* BACKWARDS INCOMPATIBLE: ChaCha20 now treats the first 4 bytes of the
  nonce as a 32-bit little-endian block counter (as defined in RFC 7539)
  and tracks the number of bytes processed. Attempting to encrypt or
  decrypt more data than the counter allows before it would overflow now
  raises a ValueError rather than silently diverging from RFC 7539.
  Setting the counter portion of the nonce to zero allows encrypting up
  to 256 GiB with a given nonce.
* BACKWARDS INCOMPATIBLE: Loading an X.509 certificate whose ECDSA or DSA
  signature AlgorithmIdentifier contains encoded NULL parameters now
  raises a ValueError. Such certificates are invalid, but older versions
  of Java emitted them; previously they loaded with a deprecation
  warning.

For full upstream changelog, see:
https://cryptography.io/en/latest/changelog/#v49-0-0

Full comparison of changes:
https://github.com/pyca/cryptography/compare/48.0.1...49.0.0

Signed-off-by: Tim Orling <tim.orling@konsulko.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>