xcb-proto: update to 1.14.1
This fixes [1] the following build error for nativesdk on Fedora 33
which is caused by the removal of fractions.gcd() in favor of math.gcd()
in python 3.9 [2]:

ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib64/python3.9/fractions.py)

Furthermore the SRC_URI is adapted as the old one doesn't provide the
1.14.1 archive.

[1] https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/commit/426ae35bee1fa0fdb8b5120b1dcd20cee6e34512
[2] https://bugs.python.org/issue39350

It's needed in gatesgarth and possibly dunfell as well to support
distributions with python-3.9 as we build libxcb-native, which is
failing with xcb-proto-1.14.

1.14.1 is a bug fix release:
https://lists.x.org/archives/xorg-announce/2020-October/003061.html

Signed-off-by: Richard Leitner <richard.leitner@skidata.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>