quilt: fix dependency on ptest-runner
Specifically when using useradd-staticids this fails without
creating a ptest user entry.

ERROR: Nothing PROVIDES 'ptest-runner' ptest-runner was skipped: Recipe ptest-runner, package ptest-runner: system username "ptest" does not have a static ID defined. Add ptest to one of these files: .../passwd
...
...
Missing or unbuildable dependency chain was: ['my-image-sdk', 'packagegroup-core-sdk', 'quilt', 'ptest-runner']

This is seen when ptest is not even enabled. We fix this by
making a conditional dependency on the ptest-runner.

Signed-off-by: Awais B <awais.belal@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>