fontconfig: disable tests
The tests require json-c library which is not explicit in build
dependencies:

../sources/fontconfig-2.17.1/test/test-conf.c:27:10: fatal error:
json.h: No such file or directory
   27 | #include <json.h>

The tests are not used so just disable them.

Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>