kernel-devsrc: copy kernel/sched/ext/ext.h
ext.h etc files were moved to new subdir in upstream commit
bba2c3615bd sched_ext: Move sources under kernel/sched/ext/

Fixes oeqa kernelmodule.py failure with 7.2 kernel:

  CC      kernel/sched/rq-offsets.s
In file included from kernel/sched/rq-offsets.c:5:
kernel/sched/sched.h:4214:10: fatal error: ext/ext.h: No such file or directory
 4214 | #include "ext/ext.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:184: kernel/sched/rq-offsets.s] Error 1
make[1]: *** [/usr/lib/modules/7.2.0-rc7-yoctodev-standard/build/Makefile:1408: prepare0] Error 2

Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>