lttng-modules: update to 2.15.3
Changes:

https://git.lttng.org/?p=lttng-modules.git;a=blob_plain;f=ChangeLog;hb=65c6bd5d4a9ef084a6c52d0728d61d10eedf9aa7

2026-08-17 LTTng modules 2.15.3
	* fix: backport: hrtimer: Reduce trace noise in hrtimer_start() (Ubuntu-6.8.0-136)
	* fix: string: Remove strncpy() from the kernel (v7.2)
	* fix: btrfs: tracepoints: trace transaction states during commit phase (v7.2)
	* fix: btrfs: tracepoints: add in_fsync field to transaction commit event (v7.2)
	* fix: btrfs: tracepoints: pass a transaction handle to transaction commit event (v7.2)
	* fix: net: constify sk_skb_reason_drop() sock parameter (v7.2)
	* fix: KVM: x86: Rename kvm_cache_regs.h => regs.h (v7.2)
	* fix: x86/msr: Remove rdmsrl() / wrmsrl() (v7.2)
	* fix: warning -Wordered-compare-function-pointers with LLVM
	* fix: warning -Wcast-function-type-strict with LLVM
	* Fix: ring buffer: zeroed UUID in populated empty packet headers

Fixes build error with kernel 7.2:

| lttng-syscalls.c: In function 'lttng_syscall_event_enabler_create_event':
| lttng-syscalls.c:612:17: error: implicit declaration of function 'strncpy' [-Wimplicit-function-declaration]
|   612 |                 strncpy(ev.name, desc->event_name, LTTNG_KERNEL_ABI_SYM_NAME_LEN - 1);
|       |                 ^~~~~~~
| lttng-syscalls.c:101:1: note: include '<string.h>' or provide a declaration of 'strncpy'
|   100 | #include <instrumentation/syscalls/syscalls_unknown.h>
|   +++ |+#include <string.h>
|   101 | #undef TRACE_SYSTEM
| lttng-syscalls.c:612:17: warning: incompatible implicit declaration of built-in function 'strncpy' [-Wbuiltin-declaration-mismatch]
|   612 |                 strncpy(ev.name, desc->event_name, LTTNG_KERNEL_ABI_SYM_NAME_LEN - 1);
|       |                 ^~~~~~~
| lttng-syscalls.c:612:17: note: include '<string.h>' or provide a declaration of 'strncpy'
| lttng-syscalls.c:704:17: warning: incompatible implicit declaration of built-in function 'strncpy' [-Wbuiltin-declaration-mismatch]
|   704 |                 strncpy(ev.name, desc->event_name, LTTNG_KERNEL_ABI_SYM_NAME_LEN - 1);
|       |                 ^~~~~~~
| lttng-syscalls.c:704:17: note: include '<string.h>' or provide a declaration of 'strncpy'

Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>