libgloss_3.0.0.bb: Fix up mv pattern to include libnosys
When installing libgloss libraries handle the ${TARGET_SYS}/lib contents
so that it is placed in ${libdir} instead of ${libdir}/lib. This
resolves a packaging QA issue.

  ERROR: libgloss-3.0.0-r0 do_package: QA Issue: libgloss:
  Files/directories were installed but not shipped in any package:
    /usr/lib/lib
    /usr/lib/lib/libnosys.a
    /usr/lib/lib/nosys.specs
  Please set FILES such that these items are packaged. Alternatively
  if they are unneeded, avoid installing them or delete them within
  do_install.
  libgloss: 3 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Nathan Rossi <nathan@nathanrossi.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>