ltp: replace 'inline' with 'static inline' for gcc 5.x
gcc 5.x defaults to -std=gnu11 instead of -std=gnu89 which causes
semantics for inline functions changes.

The standalone 'inline' causes error with gcc 5 such as:

git/testcases/kernel/syscalls/kill/kill10.c:355: undefined reference to
`k_sigaction'

Replace inline with static inline to be compatible with both gcc 4 and 5.

Found and test with configure:
SELECTED_OPTIMIZATION="-O0  -fno-omit-frame-pointer -g -pipe"

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>