squashfs-tools: package squashfs-fs.h
Needed to build the latest debian version
of android-tools
Fixes below error while building android-tools libext4_utils.mk
| squashfs_utils/squashfs_utils.c:27:10: fatal error: 'squashfs_fs.h' file not found
| #include "squashfs_fs.h"
|          ^~~~~~~~~~~~~~~
| 1 error generated.
| core2-64-poky-linux/android-tools/10.0.0.r36-r0/git/system/extras/debian/libext4_utils.mk:29: recipe for target 'build' failed
| make: *** [build] Error 1

Signed-off-by: Nisha Parrakat <Nisha.Parrakat@kpit.com>
Signed-off-by: Nisha Parrakat <nishaparrakat@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>