neon: fix fetch error
ERROR: neon-native-0.30.1-r0 do_checkuri: Fetcher failure for URL: 'http://www.webdav.org/neon/neon-0.30.1.tar.gz'. URL http://www.webdav.org/neon/neon-0.30.1.tar.gz doesn't work
ERROR: neon-native-0.30.1-r0 do_checkuri: Function failed: do_checkuri

change to https and url to OSL.
www.webdav.org is down or dean

Signed-off-by: Armin Kuster <akuster808@gmail.com>