qemu: Add missing DEPENDS on dtc
This fixes failures in builds where qemu fails with:

i586-poky-linux/qemu/1.4.0-r0/qemu-1.4.0/hw/arm/../../device_tree.c:28:20: fatal error: libfdt.h: No such file or directory
x86_64-linux/usr/libexec/i586-poky-linux/gcc/i586-poky-linux/4.7.2/ld: cannot find -lfdt

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>