btrfs-tools: upgrade 5.15.1 -> 5.16
0001-btrfs-tools-include-linux-const.h-to-fix-build-with-.patch
removed since it is included in 5.16

Add 0001-btrfs-progs-kerncompat-add-local-definition-for-alig.patch
to fix "undefined reference to `__ALIGN_KERNEL'".

Changelog:
=========
 - rescue: new subcommand clear-uuid-tree to fix failed mount due to bad uuid
   subvolume keys, caught by tree-checker
 - fi du: skip inaccessible files
 - prop: properly resolve to symlink targets
 - send, receive: fix crash after parent subvolume lookup errors
 - build:
   fix build on 5.12+ kernels due to changes in linux/kernel.h
   fix build on musl with old kernel headers
 - other:
   error handling fixes, cleanups, refactoring
   extent tree v2 preparatory work
   lots of RST documentation updates (last release with asciidoc sources),
   https://btrfs.readthedocs.io

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>