rxvt-unicode: Do not use throw specifications
Fixes build with -std=c++17

| ../../rxvt-unicode-9.22/src/../libev/ev++.h:379:46: error: ISO C++17 does not allow dynamic exception specifications
|   379 |     default_loop (unsigned int flags = AUTO) throw (bad_loop)
|       |                                              ^~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit f437b226aac498240bc1e3a02eb0257a7deeedea)
Signed-off-by: Steve Sakoman <steve@sakoman.com>