systemd-systemctl-native: disable libpam meson option
When building on rhel8.10 we got the following crash during do_compile

systemctl-259.5/src/shared/pam-util.c
| ../sources/systemd-systemctl-259.5/src/shared/pam-util.c:3:10: fatal error: security/pam_ext.h: No such file or directory
|     3 | #include <security/pam_ext.h>
|       |          ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| ninja: build stopped: subcommand failed.
| INFO: autodetecting backend as ninja

libpam is not needed for systemctl task done by bitbake, therfore
disable MESON option.

Signed-off-by: Daniel Turull <daniel.turull@ericsson.com>
[YC: On master, this is done in "systemd: upgrade to 261.1"]
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>