fontconfig: backport a patch to fix a build race
There's a build race where some objects don't explicitly depend on the
generated header ftalias.h being created:

  In file included from ../sources/fontconfig-2.17.1/src/fcpat.c:23:
  ../sources/fontconfig-2.17.1/src/fcint.h:129:12: fatal error: fcalias.h: No such file or directory
    129 | #  include "fcalias.h"

Backport a patch from upstream to add the missing dependencies.

[ YOCTO #16134 ]

Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>