at: Remove mktime signature from posixtm.c
This is in conflict with signature from system time.h

extern time_t mktime (struct tm *__tp) __THROW;

GCC-15 with C23 on, this is treated at error

 posixtm.c:45:8: error: conflicting types for 'mktime'; have 'time_t(void)' {aka 'long int(void)'}
|    45 | time_t mktime ();
|       |        ^~~~~~
|

config.h is local include file to use quotes to include it

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>