python-argparse: adding runtime dependency on python-codecs
When typing 'import argparse' in the python shell on a minimal image
with only the python-argparse recipe installed, python reports:

Python 2.7.3 (default, Jun 27 2013, 08:26:25)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import argparse;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/argparse.py", line 91, in <module>
    from gettext import gettext as _
ImportError: No module named gettext

The python-argparse recipe requires the python gettext module,
which is currently provided by python-codecs.
Hence, this commit adds python-codecs as runtime dependency to
resolve the issue.

Signed-off-by: Lukas Bulwahn <lukas.bulwahn@oss.bmw-carit.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>