mobile-broadband-provider-info: fix .pc file conflict
Issue: LIN10-4485

Error: Transaction check error:
  file /usr/share/pkgconfig/mobile-broadband-provider-info.pc from install of \
  lib32-mobile-broadband-provider-info-dev.core2_32 conflicts with file from package \
  mobile-broadband-provider-info-dev.core2_64

Signed-off-by: Zhixiong Chi <zhixiong.chi@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>