gawk: Add missing dependency on readline
building from shared state often ends up with

|
/b/kraj/angstrom/build/tmp-angstrom_next-uclibc/work/i586-angstrom-linux-uclibc/gawk/4.0.1-r1/gawk-4
.0.1/debug.c:4135: undefined reference to `rl_reset_terminal'
|
/b/kraj/angstrom/build/tmp-angstrom_next-uclibc/work/i586-angstrom-linux-uclibc/gawk/4.0.1-r1/gawk-4
.0.1/debug.c:4138: undefined reference to `rl_get_screen_size'
| debug.o: In function `unserialize':

Adding the missing readline dependency to fix such cases
where readline has not been populated in sysroot via some
other dependency and gawk would then use it or bail out.

Signed-off-by: Khem Raj <raj.khem@gmail.com>