psplash_git.bb: fix do_compile by correcting the script path
The recent change in the builddir location is breaking this recipe as
it is trying to run a script (make-image-header.sh) located in sourcedir
from builddir. As the script does not gets to run, the resulting file is
not generated causing error as seen below. This commit fixes the issue, by
providing complete path of the script.

This commit fixes this build error:

ERROR: Error executing a python function in /srv/home/nitin/prj/poky.git/meta/recipes-core/psplash/psplash_git.bb:
IOError: [Errno 2] No such file or directory: 'psplash-tlk-img.h'
ERROR: Task 6 (/srv/home/nitin/prj/poky.git/meta/recipes-core/psplash/psplash_git.bb, do_compile) failed with exit code '1'

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>