glibc - nativesdk prepare_recipe_sysroot error fix
on eSDK population, nativesdk of libnsl2 and glibc both install
yppasswd.x and yppasswd.h files which causes conflict while
preparing recipe sysroot of nativesdk-libnss-nis and nativesdk-python 3.8

The fix resolves below error
ERROR: nativesdk-libnss-nis-3.1+gitAUTOINC+062f31999b-r0 do_prepare_recipe_sysroot:
The file /opt/rdk/2.0/sysroots/x86_64-rdksdk-linux/usr/include/rpcsvc/yppasswd.x is installed by both nativesdk-libnsl2 and nativesdk-glibc, aborting
ERROR: nativesdk-libnss-nis-3.1+gitAUTOINC+062f31999b-r0 do_prepare_recipe_sysroot:
The file /opt/rdk/2.0/sysroots/x86_64-rdksdk-linux/usr/include/rpcsvc/yppasswd.h is installed by both nativesdk-libnsl2 and nativesdk-glibc, aborting