base-files/profile: change EDITOR to not be busybox specific
Setting "EDITOR=/bin/vi" breaks on non-busybox systems, as
vim will populate /usr/bin/vi instead, and you get stuff like:

  op3:~/poky/meta-builder$ git commit -s
  error: cannot run /bin/vi: No such file or directory
  error: unable to start editor '/bin/vi'
  Please supply the message using either -m or -F option.
  op3:~/poky/meta-builder$ which vi
  /usr/bin/vi
  op3:~/poky/meta-builder$

Since we've already specified a proper path above in the profile,
we've no need to call out where in the path vi lives, and hence
this will work with busybox and a full vim install w/o busybox.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>