webkitgtk: Fix compile failures with clang
Backport upstream patch to address build regression with clang

Fixes
webkitgtk-2.24.3/Source/bmalloc/bmalloc/AvailableMemory.cpp:120:31: error: implicit instantiation of undefined template 'std::__1::array<char, 256>'
        std::array<char, 256> statmBuffer;
                              ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>