shadow: disable econf
When libeconf is installed on the host and GCC from extended buildtools
is used, the host’s libeconf is detected and -DUSE_ECONF=1 gets enabled.
However, the buildtools GCC cannot see the host header files, causing
the shadow-native do_compile fail with error:
../../shadow-4.17.3/lib/getdef.c:22:10: fatal error: libeconf.h: No such file or directory

This patch disable econf to workaround above issue.

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>