bootchart2: fix installed-vs-shipped
Fixed:
ERROR: QA Issue: bootchart2: Files/directories were installed but not shipped
  /lib
  /lib/bootchart
  /lib/bootchart/bootchart-collector
  /lib/bootchart/tmpfs
  /lib/bootchart/.debug
  /lib/bootchart/.debug/bootchart-collector [installed-vs-shipped]

local.conf:
MACHINE = "qemux86-64"
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>