linux-yocto/3.10: fix drm build failure
Andrea Adami reported the following build failure:

    .../drm/drm_mm.h:105:2: error: implicit declaration of function
    'BUG_ON' [-Werror=implicit-function-declaration]
    |   BUG_ON(!hole_node->hole_follows);
    |   ^
    |   CC      drivers/pci/setup-res.o
    |   CC      drivers/gpu/drm/i915/i915_drv.o
    | cc1: some warnings being treated as errors
    | make[6]: *** [drivers/gpu/drm/ttm/ttm_agp_backend.o] Error 1
    | make[5]: *** [drivers/gpu/drm/ttm] Error 2

Cherry picking mainline commit 86e81f0e6 [drm/mm: include required headers in drm_mm.h]
fixes the build problems.

cc: Andrea Adami <andrea.adami@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>