webkitgtk: upgrade 2.50.0 -> 2.50.4
Refresh patches
- 0001-CMake-Add-a-variable-to-control-macro-__PAS_ALWAYS_I.patch
- 0001-FindGObjectIntrospection.cmake-prefix-variables-obta.patch
- 0001-Fix-build-errors-on-RISCV-https-bugs.webkit.org-show.patch
- fix-ftbfs-riscv64.patch
- reproducibility.patch
- sys_futex.patch
- t6-not-declared.patch

Drop backport fix-musl-compilation.patch which already exists
in 2.50.4

Signed-off-by: Alexander Kanavin <alex@linutronix.de>

- Fix compile failure on qemux86 [1] to
drop fix_op_instanceof_handler_for_32-bit_C-loop_build.patch,
which conflicts with upstream solution [2]

- Fix compile failure on qemuriscv64
...
Source/ThirdParty/skia/modules/skcms/src/Transform_inl.h:810:71: error: cannot tail-call: tail call production failed
  810 |         DECLARE_STAGE(name, arg, [[clang::musttail]] return (*list.fn)(list, ctx, src, dst, \
      |                                                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
  811 |                                                                        r, g, b, a, i))
      |                                                                        ~~~~~~~~~~~~~~
...

[1] https://autobuilder.yoctoproject.org/valkyrie/#/builders/6/builds/2907
[2] https://github.com/WebKit/WebKit/commit/fcaa289f6015595a638eb96b9f728eaaa7b13ab8

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>