nghttp2: fix for multilib support
Update package name to fix following error:
ERROR: Required build target 'lib32-core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['lib32-core-image-minimal', 'lib32-libnghttp2']

for lib32 image, lib{PN} will be expanded as lib32-liblib32-nghttp2, so
above error occurs, update lib{PN} to lib{BPN} to fix it.

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>