glibc: Drop 0022-Avoid-hardcoded-build-time-paths-in-the-output-binar.patch
This patch was originally added to replace pwd-derived paths in glibc test binaries with
fixed Yocto paths (e.g., $(oe_srcdir), $(libdir)/glibc-tests/ptest/tests/glibc-ptest) to
fix the repro issue with run-ptest script(no longer exists in master).

In the current master:
run-ptest script and the glibc-y2038-tests recipe were dropped via the following commit
https://git.openembedded.org/openembedded-core/commit/meta?id=fbe3679ba3c12c52a502511f5dde91fb4de7a6b6
Glibc tests now run via check-test-wrapper, which dynamically configures environment,
sysroot, and library paths. The hardcoded paths from this patch conflict with dynamic
path resolution, causing some tests to fail like

error: xdlmopen.c:28: error: dlmopen:/usr/lib/glibc-tests/ptest/tests/glibc-ptest/*:
cannot open shared object file:No such file or directory

Reproducibility is confirmed to remain intact without this patch. Since it no longer provides
benefits and interferes with correct test execution, the patch is being dropped.

Testing results:

            before   after   diff
PASS         6937     6943     +6
XPASS           4        4      0
FAIL           72       66     -6
XFAIL          16       16      0
UNSUPPORTED   108      108      0

Signed-off-by: Deepesh Varatharajan <Deepesh.Varatharajan@windriver.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>