python-git: Add missing dependency
Python-git depends on getpass, which is part of python-unixadmin.

If it is missing:

root@qt5022:~# python
Python 2.7.9 (default, Nov 12 2015, 17:41:32)
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/git/__init__.py", line 35, in <module>
    from git.config import GitConfigParser
  File "/usr/lib/python2.7/site-packages/git/config.py", line 21, in <module>
    from git.util import LockFile
  File "/usr/lib/python2.7/site-packages/git/util.py", line 14, in <module>
    import getpass
ImportError: No module named getpass
>>>

Reported-by: Dimitrios Katsaros <patcherwork@gmail.com>
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>