tcl: extend to nativesdk
Fixed:
$ bitbake nativesdk-expect
ERROR: Nothing PROVIDES 'nativesdk-tcl' (but virtual:nativesdk:expect_5.45.bb DEPENDS on or otherwise requires it). Close matches:
[snip]

(From OE-Core rev: 5c950c509edcc50d39a1f426579b354d97178ff2)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>