libuv: upgrade 1.43.0 -> 1.44.1
License-Update:
the following message removed from LICENSE:
android-ifaddrs.h, android-ifaddrs.c, copyright Berkeley Software Design
Inc, Kenneth MacKay and Emergya (Cloud4all, FP7/2007-2013, grant agreement
n° 289016). Three clause BSD license.

Changes since version 1.43.0:
=============================
* process: simplify uv__write_int calls
* macos: don't use thread-unsafe strtok()
* process: fix hang after NOTE_EXIT
* darwin: remove EPROTOTYPE error workaround
* doc: fix v1.43.0 changelog entries
* win: replace CRITICAL_SECTION+Semaphore with SRWLock
* darwin: translate EPROTOTYPE to ECONNRESET
* android: use libc getifaddrs()
* unix: fix STATIC_ASSERT to check what it means to check
* unix: ensure struct msghdr is zeroed in recvmmsg
* test: test with maximum recvmmsg buffer
* unix: don't allow too small thread stack size
* bsd: ensure mutex is initialized
* doc: add gengjiawen as maintainer
* process: monitor for exit with kqueue on BSDs
* test: fix flaky uv_fs_lutime test
* build: fix cmake install locations
* thread,win: fix C90 style nit
* build: rename CFLAGS to AM_CFLAGS
* doc/guide: update content and sample code
* process,bsd: handle kevent NOTE_EXIT failure
* test: remove flaky test ipc_closed_handle
* darwin: bump minimum supported version to 10.15
* win: return fractional seconds in uv_uptime()
* build: export uv_a for cmake
* loop: add pending work to loop-alive check
* win: use GetTickCount64 for uptime again
* win: restrict system DLL load paths
* win,errors: remap ERROR_ACCESS_DENIED to UV_EACCES
* bench: add 'uv_queue_work' ping-pong measurement
* build: fix error C4146 on MSVC
* test: fix benchmark-ping-udp
* win,fs: consider broken pipe error a normal EOF
* document the values of enum uv_stdio_flags
* win,loop: add missing uv_update_time
* win,fs: avoid closing an invalid handle
* fix oopsie from
* doc: clarify android api level
* win: fix style nits [NFC]
* test: fix flaky udp_mmsg test
* test: fix ipc_send_recv_pipe flakiness
* doc: checkout -> check out
* core: change uv_get_password uid/gid to unsigned
* hurd: unbreak build on GNU/Hurd
* freebsd: use copy_file_range() in uv_fs_sendfile()
* test: use closefd in runner-unix.c
* Reland "macos: use posix_spawn instead of fork"
* android: fix build error when no ifaddrs.h
* unix,win: add uv_available_parallelism()
* process: remove OpenBSD from kevent list
* zos: fix build breakage
* process: only use F_DUPFD_CLOEXEC if it is defined
* win,poll: add the MSAFD GUID for AF_UNIX
* unix: simplify uv__cloexec_fcntl()
* doc: add secondary GPG ID for vtjnash
* unix: remove uv__cloexec_ioctl()

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>