python3-magic: add missing DEPENDS
Since file-native is ASSUME_PROVIDED magic.mgc is not being staged.  As
a result diffoscope-native is failing with:

magic.MagicException: b'could not find any valid magic files!

Fix this by adding dependency on file-replacement-native

Signed-off-by: Steve Sakoman <steve@sakoman.com>