lttng-modules: Fix trace_hrtimer_start build failure
Fix the following build failure

probes/../../include/lttng/tracepoint-event-impl.h:133:6: error: conflicting
types for 'trace_hrtimer_start'; have 'void(struct hrtimer *, enum hrtimer_mode)'
  133 | void trace_##_name(_proto);
      |      ^~~~~~

Signed-off-by: He Zhe <zhe.he@windriver.com>
[YC: this is a partial backport of
commit 7dae5f40e394 ("lttng-modules: fix build against kernel 7.1+")]
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>