ppp: make pam optional to avoid host contamination
Without explicitly disabling pam in ppp, it will check the host for
pam headers. This leads to this QA error:

ERROR: ppp-2.5.1-r0 do_configure: QA Issue: This autoconf log
indicates errors, it looked at host include and/or library paths
while determining system capabilities.
Rerun configure task after fixing this. [configure-unsafe]

This is a somewhat difficult to hit, only my test machines that have
the pam dev package installed show it.

Fix this by adding a packageconfig for pam, with its default value
off, since enabling PAM is completely untested.

Signed-off-by: Dan McGregor <dan.mcgregor@usask.ca>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>