valgrind: depends on boost when ptest
Fixed:
drd/tests/boost_thread.cpp:5:38: fatal error: boost/thread/condition.hpp: No such file or directory
 #include <boost/thread/condition.hpp>

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>