alsa-lib: topology: Add missing include sys/stat.h
Fixes this build error with uclibc:

alsa-lib-1.1.0/src/topology/parser.c: In function 'snd_tplg_build_file':
alsa-lib-1.1.0/src/topology/parser.c:262:35: error: 'S_IRUSR' undeclared
(first use in this function)
open(outfile, O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);

Signed-off-by: Maxin B. John <maxin.john@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>