Revert "scripts/install-buildtools: Update to 5.0.16"
This reverts commit 917c382c412766b40779788ee2411ac23358f0ae.

I mechanically did the update but should not have: this was already
raised here:
Re: [OE-core] Wrong version of buildtools files uploaded for 5.0.16.
https://lore.kernel.org/all/DH2QPDTPQT3Q.1TJYOVQ7PIU7B@smile.fr/

Trying to fetch the 5.0.16 buildtools installer results in an error:

    $ ./scripts/install-buildtools
    INFO: Fetching buildtools installer
    ERROR: Could not download file from https://downloads.yoctoproject.org/releases/yocto/yocto-5.0.16/buildtools/x86_64-buildtools-extended-nativesdk-standalone-5.0.16.sh

See https://downloads.yoctoproject.org/releases/yocto/yocto-5.0.16/RELEASENOTES:
> ---------------
>  Known Issues
> ---------------
> The poky DISTRO_VERSION was incorrectly left at 5.0.15. This is a minor issue, if a workaround is needed please cherry-pick:
>  - poky commit 06210079b2e10d6d3fb943afe87864267e329821, or
>  - meta-yocto commit 03f93c769ec99e5086e492d8145eb308a718e8d3.

Signed-off-by: Yoann Congal <yoann.congal@smile.fr>
Signed-off-by: Paul Barker <paul@pbarker.dev>