screen: add back the patch for parallel build
The patch 0001-fix-for-multijob-build.patch was removed by:
"d437921 screen: upgrade to 4.4.0"

But in fact the fixes is not all in the version 4.4.0, we
still get errors in parallel builds:

| ../screen-4.4.0/screen.h:48:18: fatal error: comm.h: No such file or directory

So rebase the patch and add it back.

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>