qemu-native: add direct dependency on ninja-native and meson-native
* with many native dependencies excluded in:
  layer.conf: Extend recipes not to install without explict dependencies
  this was now failing with:
  ERROR: Cannot find Ninja
  and after adding ninja-native to DEPENDS it was failing due to missing meson as well:
  /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qemu-native/6.0.0-r0/qemu-6.0.0/configure: 6415: --version: not found
  /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qemu-native/6.0.0-r0/qemu-6.0.0/configure: 6418: setup: not found

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>