gst-plugins-base: Fix mulitlib packaging
Updated FILES to contain MLPREFIX since this is a dyanmic assignment
and cannot automatically be fixed.

ERROR: QA Issue: lib32-gstreamer1.0-plugins-base: Files/directories were installed but not shipped
  /usr/share/gst-plugins-base/1.0/license-translations.dict [installed-vs-shipped]

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>