ltp: Don't link against libfl
We have already defined yywrap function in scan.l file. After this, we no
longer need to link against libfl.
Since we are using --as-needed by default in linker, which means we end
up with errors like

	libfl.so: undefined reference to `yylex'

Signed-off-by: Chong Lu <Chong.Lu@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>