packagegroup-core-tools-profile: Disable lttng-modules for riscv64
with 5.8+ kernel it seems lttng-modules needs kprobes which are not
there yet for riscv64

Fixes
lttng-modules-2.12.2/wrapper/kallsyms.c:20:3: error: #error "LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0"
   20 | # error "LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0"
      |   ^~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>