bluez-hcidump: upgrade from 2.0 to 2.1
[YOCTO #1371]

Recently bluez4 was updated from 4.82 to 4.96 and bluez-hcidump can't build:
src/hcidump.c:54:24: error: redefinition of 'ntoh64'.

In 2.1 the duplicated definition of ntoh64 was removed.

Signed-off-by: Dexuan Cui <dexuan.cui@intel.com>