packagegroup-core-weston.bb: add pam to REQUIRED_DISTRO_FEATURES
* weston, weston-init, weston-examples require pam
* fixes:
  ERROR: Nothing RPROVIDES 'weston-init' (but meta/recipes-graphics/packagegroups/packagegroup-core-weston.bb RDEPENDS on or otherwise requires it)
  weston-init was skipped: missing required distro feature 'pam' (not in DISTRO_FEATURES)
  NOTE: Runtime target 'weston-init' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['weston-init']
  ERROR: Nothing RPROVIDES 'packagegroup-core-weston' (but meta/recipes-graphics/packagegroups/packagegroup-core-weston.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'packagegroup-core-weston'
  NOTE: Runtime target 'packagegroup-core-weston' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-core-weston']
  ERROR: Nothing RPROVIDES 'weston-examples' (but meta/recipes-graphics/packagegroups/packagegroup-core-weston.bb RDEPENDS on or otherwise requires it)
  weston RPROVIDES weston-examples but was skipped: missing required distro feature 'pam' (not in DISTRO_FEATURES)
  NOTE: Runtime target 'weston-examples' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['weston-examples']
  ERROR: Nothing RPROVIDES 'weston' (but meta/recipes-graphics/packagegroups/packagegroup-core-weston.bb RDEPENDS on or otherwise requires it)
  weston was skipped: missing required distro feature 'pam' (not in DISTRO_FEATURES)
  NOTE: Runtime target 'weston' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['weston']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>