eglibc: Add patch to fix /var installation location
This address the packaging issues since it's installed in the wrong place
ERROR: For recipe eglibc-nativesdk, the following files/directories were installed but not shipped in any package:
ERROR:   /var
ERROR:   /var/db
ERROR:   /var/db/Makefile

Signed-off-by: Saul Wold <sgw@linux.intel.com>