packagegroup-core-standalone-sdk-target: remove qemuwrapper-cross
Remove qemuwrapper-cross from RDEPENDS, install a cross pkg in sysroots
isn't useful, if we really need run qemuwrapper in SDK, we should add it
as nativesdk, and it has multilib conflicts when populate_ sdk:

error: file /usr/bin/crossscripts/qemuwrapper from install of
qemuwrapper-cross-1.0-r0.lib32_x86 conflicts with file from package
qemuwrapper-cross-1.0-r0.core2_64

[YOCTO #8089]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>