gcc: Undef _TIME_BITS in sanitizer_procmaps_solaris.cpp
gcc-sanitizers fail to build when both -D_TIME_BITS=64 and
-D_FILE_OFFSET_BITS=64  are defined. This is because
sanitizer_procmaps_solaris.cpp explicitly undefines  _FILE_OFFSET_BITS
before including any headers, which causes _TIME_BITS=64 to  violate the
requirement in glibc:

/usr/include/features-time64.h:26:5: error:  "_TIME_BITS=64 is allowed
only with _FILE_OFFSET_BITS=64"

Fixes a build failure on 32-bit Linux platforms when using both
-D_TIME_BITS=64 and -D_FILE_OFFSET_BITS=64.

Signed-off-by: Jiaying Song <jiaying.song.cn@windriver.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>