python3-pygobject: fix compile error with old GCC
If the build is done with GCC 10 (eg a native build on Debian 11) then
the build fails:

  gi/pygi-resulttuple.c:337:1: error: label at end of compound statement

Backport a patch from upstream to add a missing semicolon.

[ YOCTO #16147 ]

Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>