weston: add pam to REQUIRED_DISTRO_FEATURES
* it was added to weston-init in 72dd74c5d384dbe641cc7c02ecf766ff8d5f555f now world
  builds are failing with:

  ERROR: Nothing RPROVIDES 'weston-init' (but openembedded-core/meta/recipes-graphics/wayland/weston_9.0.0.bb RDEPENDS on or otherwise requires it)
  weston-init was skipped: missing required distro feature 'pam' (not in DISTRO_FEATURES)
  NOTE: Runtime target 'weston-init' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['weston-init']
  ERROR: Nothing RPROVIDES 'weston-dev' (but openembedded-core/meta/recipes-graphics/wayland/weston_9.0.0.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'weston-dev'
  NOTE: Runtime target 'weston-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['weston-dev']
  ERROR: Nothing RPROVIDES 'weston' (but openembedded-core/meta/recipes-graphics/wayland/weston_9.0.0.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'weston'
  NOTE: Runtime target 'weston' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['weston']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>