license_image.bbclass: report all packages with incompatible license
When multiple packages cannot be installed it shows only first one it
finds, because of bb.fatal use. It might require many iterations to find
all packages to avoid.

e.g. with ptest enabled and GPL-3.0-or-later, GPL-3.0-only set as
incompatible licenses you might get list like this for relatively small
image:

ERROR: image-1.0-r0 do_rootfs: Some packages cannot be installed into the image because they have incompatible licenses:
        bzip2-ptest (GPL-3.0-or-later)
        coreutils (GPL-3.0-or-later)
        coreutils-stdbuf (GPL-3.0-or-later)
        diffutils (GPL-3.0-or-later)
        findutils (GPL-3.0-or-later)
        gawk (GPL-3.0-or-later)
        gnutls-openssl (GPL-3.0-or-later)
        gnutls-ptest (GPL-3.0-or-later)
        grep (GPL-3.0-only)
        make (GPL-3.0-only)
        mpfr (LGPL-3.0-or-later)
        python3-dbusmock (GPL-3.0-only)
        readline (GPL-3.0-or-later)
        sed (GPL-3.0-or-later)

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>