classes/compress_doc: add missing import subprocess
Enabling compress_doc gives the following stack trace:

File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:package_do_compress_doc(d)
     0003:
File: '/scratch/yocto/swupd.bb/poky/meta/classes/compress_doc.bbclass', lineno: 50, function: package_do_compress_doc
     0046:    mandir = os.path.abspath(dvar + os.sep + d.getVar("mandir"))
     0047:    if os.path.exists(mandir):
     0048:        # Decompress doc files which format is not compress_mode
     0049:        decompress_doc(mandir, compress_mode, decompress_cmds)
 *** 0050:        compress_doc(mandir, compress_mode, compress_cmds)
     0051:
     0052:    infodir = os.path.abspath(dvar + os.sep + d.getVar("infodir"))
     0053:    if os.path.exists(infodir):
     0054:        # Decompress doc files which format is not compress_mode
File: '/scratch/yocto/swupd.bb/poky/meta/classes/compress_doc.bbclass', lineno: 180, function: compress_doc
     0176:                    _collect_hardlink(hardlink_dict, file)
     0177:                # Normal file
     0178:                elif os.path.isfile(file):
     0179:                    cmd = "%s %s" % (compress_cmds[compress_mode], file)
 *** 0180:                    (retval, output) = subprocess.getstatusoutput(cmd)
     0181:                    if retval:
     0182:                        bb.warn("compress failed %s (cmd was %s)%s" % (retval, cmd, ":\n%s" % output if output else ""))
     0183:                        continue
     0184:                    bb.note('compress file %s' % file)
Exception: NameError: name 'subprocess' is not defined

Fix by adding the missing import in two places.

Signed-off-by: André Draszik <andre.draszik@jci.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>