gcc: Refresh patch to fix patch fuzz
This is due to previous patches editing common files from this patch

Fixes
ERROR: gcc-source-11.1.0-11.1.0-r0 do_patch: Fuzz detected:

Applying patch 0028-Add-ssp_nonshared-to-link-commandline-for-musl-targe.patch
patching file gcc/config/linux.h
Hunk #1 succeeded at 203 with fuzz 1 (offset 8 lines).
patching file gcc/config/rs6000/linux.h
patching file gcc/config/rs6000/linux64.h

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>