common-clang.inc: fix undefined name in get_clang_arch
Replace arch_val by arch_var, thus fixing:

NameError: name 'arch_val' is not defined. Did you mean: 'arch_var'?

Signed-off-by: João Marcos Costa <joaomarcos.costa@bootlin.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>