wpa-supplicant: add patch to check for kernel header version when compiling macsec
When using Arm binary toolchain, version 2.11 of wpa-supplicant is
failing to compile with the following error:

| ../src/drivers/driver_macsec_linux.c:81:29: error: field ‘offload’ has incomplete type
|    81 |         enum macsec_offload offload;
|       |

Backport a recent patch that corrects the issue by adding a check for
the version of kernel headers being used in compilation and disabling
that enum if too old a version is being used (or is used by the
binary toolchain).

Signed-off-by: Jon Mason <jdmason@kudzu.us>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>