linux-yocto/5.15: update to v5.15.129
Updating  to the latest korg -stable release that comprises
the following commits:

    9e43368a3393 Linux 5.15.129
    d48016d74836 mm,ima,kexec,of: use memblock_free_late from ima_free_kexec_buffer
    1c41cd30d5cd mm: memory-failure: fix unexpected return value in soft_offline_page()
    0712721e4f4f mm: memory-failure: kill soft_offline_free_page()
    efd02b5cadd5 dma-buf/sw_sync: Avoid recursive lock during fence signal
    8dbf913520c4 pinctrl: renesas: rza2: Add lock around pinctrl_generic{{add,remove}_group,{add,remove}_function}
    f1c0402b8e22 clk: Fix undefined reference to `clk_rate_exclusive_{get,put}'
    10bc3eddc605 scsi: core: raid_class: Remove raid_component_add()
    d3d57cdbfda4 scsi: snic: Fix double free in snic_tgt_create()
    ef56cc8889be can: raw: add missing refcount for memory leak fix
    930f3f164964 drm/i915: Fix premature release of request's reusable memory
    3cb86cc565df cgroup/cpuset: Free DL BW in case can_attach() fails
    ffff4fc4bad7 sched/deadline: Create DL BW alloc, free & check overflow interface
    86aa90795979 cgroup/cpuset: Iterate only if DEADLINE tasks are present
    43d8cbfefa7c sched/cpuset: Keep track of SCHED_DEADLINE task in cpusets
    d0eb4917f4d3 sched/cpuset: Bring back cpuset_mutex
    918879de0e23 cgroup/cpuset: Rename functions dealing with DEADLINE accounting
    78efab71a649 torture: Fix hang during kthread shutdown phase
    c8fb97dd7fe6 nfsd: use vfs setgid helper
    01966511868e nfs: use vfs setgid helper
    a7a1849899aa x86/fpu: Set X86_FEATURE_OSXSAVE feature after enabling OSXSAVE in CR4
    ad79f943c869 x86/fpu: Invalidate FPU state correctly on exec()
    b190cf1f277a drm/display/dp: Fix the DP DSC Receiver cap size
    c8aab333d41a drm/vmwgfx: Fix shader stage validation
    b53ed415163e PCI: acpiphp: Use pci_assign_unassigned_bridge_resources() only for non-root bus
    60ba1bfa036a media: vcodec: Fix potential array out-of-bounds in encoder queue_setup
    544cd10defa1 of: dynamic: Refactor action prints to not use "%pOF" inside devtree_lock
    f1d4a5881856 of: unittest: Fix EXPECT for parse_phandle_with_args_map() test
    ce66cd478636 radix tree: remove unused variable
    898c8c5b1114 lib/clz_ctz.c: Fix __clzdi2() and __ctzdi2() for 32-bit kernels
    ff90a4c6edf8 batman-adv: Hold rtnl lock during MTU update via netlink
    ea38c0d9aaa2 batman-adv: Fix batadv_v_ogm_aggr_send memory leak
    7f3f72eb8f5b batman-adv: Fix TT global entry leak when client roamed back
    f7667b49880a batman-adv: Do not get eth header before batadv_check_management_packet
    3f9312dd7581 batman-adv: Don't increase MTU when set by user
    cde5a240d72d batman-adv: Trigger events for auto adjusted MTU
    22426e1ce679 selinux: set next pointer before attaching to list
    711595bfdccf nfsd: Fix race to FREE_STATEID and cl_revoked
    bd1697e12230 NFS: Fix a use after free in nfs_direct_join_group()
    5f642613746e mm: add a call to flush_cache_vmap() in vmap_pfn()
    440c10034b4d ALSA: ymfpci: Fix the missing snd_card_free() call at probe error
    5cc7d81cf576 clk: Fix slab-out-of-bounds error in devm_clk_release()
    0f72859acfa2 NFSv4: Fix dropped lock for racing OPEN and delegation return
    9c025420fef2 ibmveth: Use dcbf rather than dcbfl
    7e546bd08943 Revert "KVM: x86: enable TDP MMU by default"
    67af12f5582b net/ncsi: change from ndo_set_mac_address to dev_set_mac_address
    4451457d61e0 net/ncsi: make one oem_gma function for all mfr id
    f683f4be802b bonding: fix macvlan over alb bond support
    0fa8046e923a net: remove bond_slave_has_mac_rcu()
    f0ec97fca629 rtnetlink: Reject negative ifindexes in RTM_NEWLINK
    00247cfd2b69 rtnetlink: return ENODEV when ifname does not exist and group is given
    75cfb7de44e5 netfilter: nf_tables: fix out of memory error handling
    f22954f8c58f netfilter: nf_tables: flush pending destroy work before netlink notifier
    ff34403fef98 net/sched: fix a qdisc modification with ambiguous command request
    30624ea3f8b6 igc: Fix the typo in the PTM Control macro
    f697c3ead109 igb: Avoid starting unnecessary workqueues
    d7823d752ce1 ice: fix receive buffer size miscalculation
    ace1b0ae3097 net: validate veth and vxcan peer ifindexes
    335be585416d net: bcmgenet: Fix return value check for fixed_phy_register()
    60a5034584ea net: bgmac: Fix return value check for fixed_phy_register()
    5b52c9ba42c0 ipvlan: Fix a reference count leak warning in ipvlan_ns_exit()
    2bad37b6f675 dccp: annotate data-races in dccp_poll()
    9b015360e86f sock: annotate data-races around prot->memory_pressure
    c52c6c0223e1 octeontx2-af: SDP: fix receive link config
    ce6e2b14bc09 tracing: Fix memleak due to race between current_tracer and trace
    ef748360ba91 tracing: Fix cpu buffers unavailable due to 'record_disabled' missed
    fdf5804d7475 can: raw: fix lockdep issue in raw_release()
    278fccf587dd drm/amd/display: check TG is non-null before checking if enabled
    a955e6a0e39d drm/amd/display: do not wait for mpc idle if tg is disabled
    e0bd4f0c60b4 can: raw: fix receiver memory leak
    b832174b7f89 jbd2: fix a race when checking checkpoint buffer busy
    9c31bb2684f8 jbd2: remove journal_clean_one_cp_list()
    d91783e6864a jbd2: remove t_checkpoint_io_list
    a0ab49e7a758 ALSA: pcm: Fix potential data race at PCM memory allocation helpers
    2e56d380daa9 fbdev: fix potential OOB read in fast_imageblit()
    14163f4a4fa6 fbdev: Fix sys_imageblit() for arbitrary image widths
    5b60bd9081a9 fbdev: Improve performance of sys_imageblit()
    166f0bf4560b MIPS: cpu-features: Use boot_cpu_type for CPU type based features
    8f106e97409d MIPS: cpu-features: Enable octeon_cache by cpu_type
    d1d0b239f974 fs: dlm: fix mismatch of plock results from userspace
    77d334c44681 fs: dlm: use dlm_plock_info for do_unlock_close
    f9a33cc7d946 fs: dlm: change plock interrupted message to debug again
    7ac088841ffb fs: dlm: add pid to debug log
    df9c842ab0a4 dlm: replace usage of found with dedicated list iterator variable
    33e9c610e337 dlm: improve plock logging if interrupted
    d9ce077f8b1f PCI: acpiphp: Reassign resources on bridge if necessary
    8cc8645dd3e1 xprtrdma: Remap Receive buffers after a reconnect
    91a707507e83 NFSv4: fix out path in __nfs4_get_acl_uncached
    323b830eebd1 NFSv4.2: fix error handling in nfs42_proc_getxattr
    5de0a325c45e objtool/x86: Fix SRSO mess

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>