systemd: Make libnss-mymachines conditional upon packageconfig
nss-mymachines packageconfig controls this features therefore add this
dependency only when it is enabled.

Fixes
    ERROR: systemd-1_254.4-r0 do_package_qa: QA Issue: systemd-container rdepends on libnss-mymachines, but it isn't a build dependency? [build-deps]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Cc: Florian Wickert <fw@ferncast.de>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>