mmc-utils: upgrade to latest revision
Fixes build error: when using Linux 5.4 kernel:

In function read_extcsd: mmc_cmds.c:72:18: error: MMC_BLOCK_MAJOR
undeclared (first use in this function)

This SRCREV bump includes two commits:

b7e4d5a mmc-utils: Add General command CMD56 read support
0d493fb mmc-utils: Fix build error MMC_BLOCK_MAJOR undeclared

Signed-off-by: Alexander Kanavin <alex@linutronix.de>
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit d98b06c9c6f480de1e5167bfe8392e39300fc02c)
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>