python3-docutils: fix interpreter lines
when compiling a non native variant, latest update
introduced package-qa errors like

ERROR: QA Issue: .../docutils/utils/smartquotes.py contained in package
nativesdk-python3-docutils requires /usr/bin/python3, but no providers
found in RDEPENDS:nativesdk-python3-docutils? [file-rdeps]

Fix that by patching the interpreter lines after install

Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>