nfs-utils: upgrade 2.9.1 -> 2.9.2
ChangeLog: https://www.kernel.org/pub/linux/utils/nfs-utils/2.9.2/2.9.2-Changelog

Drop 0001-fh_key_file.c-Fix-build-error-for-musl.patch (fixed upstream).

Add patches to fix build failures:
- Fix link error with --disable-nfsdctl (undefined reference to
  nfsd_nl_cmd_str)
- Fix musl build (missing stddef.h for offsetof in getport.c)

Both reported to linux-nfs@vger.kernel.org.

Signed-off-by: Jaipaul Cheernam <jaipaul.cheernam@est.tech>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>