rt-tests: set branch name in SRC_URI
Upstream repo no longer has 'master' branch, and switched to
'main'. To avoid issue such as:

ERROR: rt-tests-1_1.1-r0 do_fetch: Fetcher failure: Unable to find
revision dff174f994f547a5785d32454865f140daacb0f5 in branch master
even from upstream

we need to set the default branch name to 'main' in the recipe.

Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
Signed-off-by: Steve Sakoman <steve@sakoman.com>