boost: Fix build on soft-float ABI arm systems
We get errors like
./boost/test/execution_monitor.hpp:490:27: error: 'FE_DIVBYZERO' was not
declared in this scope
     BOOST_FPE_DIVBYZERO = FE_DIVBYZERO,

on musl, rightly because FPU is not used on soft-float
systems

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>