perf: add PACKAGECONFIG for llvm
for avoiding to enable llvm option under uncommon condition,
make llvm controll under PACKAGECONFIG.

error log:
ERROR: perf-1.0-r2 do_package_qa: QA Issue: /usr/bin/trace contained in package perf requires libLLVM.so.2x.x(LLVM_2x.x)(64bit), but no providers found in RDEPENDS:perf? [file-rdeps]

Signed-off-by: Li Wang <li.wang@windriver.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
(cherry picked from commit a7c0c0f18a61d15c101c7c345de44c94043ae39a)
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>