lib/oe/lsb: Add missing os import
  File "/srv/pokybuild/yocto-worker/buildperf-alma8/build/layers/openembedded-core/meta/lib/oe/lsb.py", line 11, in get_os_release
    if os.path.exists('/etc/os-release'):
       ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>