libsolv: fix installed-vs-shipped for nativesdk
Fixed:
ERROR: nativesdk-libsolv-0.6.19-r0 do_package: QA Issue: nativesdk-libsolv: Files/directories were installed but not shipped in any package:
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man3
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man1
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man3/libsolv-constantids.3
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man3/libsolv.3
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man3/libsolv-history.3
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man3/libsolv-pool.3
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man3/libsolv-bindings.3
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man1/mergesolv.1
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man1/testsolv.1
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man1/installcheck.1
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/man/man1/dumpsolv.1

It checks ${CMAKE_INSTALL_PREFIX}/share/man when configure, but it may
not exist when crosscompile, for example, when CMAKE_INSTALL_PREFIX="/",
it is OK, but when CMAKE_INSTALL_PREFIX="/some/path/else", then it
doesn't exist, and the man dir would be set to "/usr/man" which is
incorrect.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>