mesa: Upgrade to 17.1.4 release
This includes following upstream bug fixes:

Bug 77240 - khrplatform.h not installed if EGL is disabled
Bug 95530 - Stellaris - colored overlay of sectors doesn't render on i965
Bug 96958 - [SKL] Improper rendering in Europa Universalis IV
Bug 99467 - [radv] DOOM 2016 + wine. Green screen everywhere (but can be started)
Bug 101071 - compiling glsl fails with undefined reference to `pthread_create'
Bug 101252 - eglGetDisplay() is not thread safe
Bug 101294 - radeonsi minecraft forge splash freeze since 17.1
Bug 101451 - [G33] ES2-CTS.functional.clipping.polygon regression

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
Signed-off-by: Ross Burton <ross.burton@intel.com>