send-error-report: Fix dubious error reporting
Currently this code prints things like:

ERROR: OK

which is unhelpful at best. After this change it would print:

ERROR: HTTP Error 500

which at least gives us something to work on.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>