diffutils: allow native & nativesdk builds
Required by the new dtc rdepends to avoid errors like this:

ERROR: Required build target 'ionel-rpi-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['ionel-rpi-image', 'nativesdk-packagegroup-sdk-host', 'nativesdk-qemu', 'nativesdk-dtc', 'nativesdk-diffutils']

Signed-off-by: Ioan-Adrian Ratiu <adi@adirat.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>