python2-manifest: Add missing xmlrpclib.py
The manifest creation bug that was masking this file was fixed, rerun and add
the missing file to fix:

  File "/usr/lib64/python2.7/SimpleXMLRPCServer.py", line 102, in <module>
    import xmlrpclib
ImportError: No module named xmlrpclib

[YOCTO #12814]

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>