uki.bbclass: fix UKI_DEVICETREE usage
Set KERNEL_DEVICETREE to empty string with weakest assignment
if machine does not set this. This changes UKI_DEVICETREE
to an empty string by default and fixes genericarm64 uki image builds:

ERROR: ERROR: cannot find /home/builder/src/core/build/tmp/deploy/images/genericarm64/${KERNEL_DEVICETREE}.

Also remove UKI_DEVICETREE setting in wic and uki oeqa selftests since the
class now handles it correctly.

Tested-by: Jon Mason <jon.mason@arm.com>
Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>