libevent: fix the multilib header conflict
Error: Transaction check error:
  file /usr/include/event2/event-config.h conflicts between attempted installs of libevent-dev-2.1.8-r0.skylake_64 and lib32-libevent-dev-2.1.8-r0.x86

The conflict is the size macro definition between 32bit and 64bit
such as:
< #define EVENT__SIZEOF_LONG 8
> #define EVENT__SIZEOF_LONG 4
< #define EVENT__SIZEOF_PTHREAD_T 8
> #define EVENT__SIZEOF_PTHREAD_T 4

Signed-off-by: Zhixiong Chi <zhixiong.chi@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>