nospdx: also drop do_create_recipe_sbom
create-spdx-3.0 adds do_create_recipe_sbom, which assembles the recipe
SBOM from the SPDX document produced by do_create_recipe_spdx.

nospdx deletes do_create_recipe_spdx but leaves do_create_recipe_sbom
in, so on a recipe that inherits nospdx it has no SPDX document to read
and, if executed, fails with:

  ERROR: meta-world-pkgdata-1.0-r0 do_create_recipe_sbom: Could not find
  a static SPDX document named static-meta-world-pkgdata

do_create_recipe_sbom is reachable via sbom-cve-check-recipe.bbclass or
explicit "bitbake -c create_recipe_sbom". In those cases nospdx recipes
such as meta-world-pkgdata break. Delete it alongside the other recipe
SPDX task.

Signed-off-by: Hiago De Franco <hfranco@baylibre.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 4478086b7b13ec365dfb4b2335fb35013e8ceea0)
Signed-off-by: Yoann Congal <yoann.congal@smile.fr>