qemu-native: only depends on libxext-native when x11
Fixed when build without x11 in DISTRO_FEATURES:
ERROR: libxext-native was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>