at: fix configure option with/without-selinux
without-selinux doesn't work since WITH_SELINUX is always be defined no
matter which option is given: with-selinux, without-selinux.

This causes build errors if '--without-selinux' is used and libselinux
is not buildable in project:

  atd.c:87:29: fatal error: selinux/selinux.h: No such file or directory

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>