libcheck: fix file-rdeps QA issue
* Fixes:
  ERROR: nativesdk-libcheck-0.10.0-r0 do_package_qa: QA Issue:
  /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/checkmk
  contained in package nativesdk-libcheck requires
  /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/gawk,
  but no providers found in RDEPENDS_nativesdk-libcheck? [file-rdeps]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Peter Kjellerstedt <peter.kjellerstedt@axis.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>