bdwgc: installed-vs-shipped for nativesdk
Fixed:
ERROR: nativesdk-bdwgc-7.4.2-r0 do_package: QA Issue: nativesdk-bdwgc: Files/directories were installed but not shipped in any package:
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/share
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/share/gc
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/share/gc/porting.html
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/share/gc/gcinterface.html
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/share/gc/gcdescr.html
  /opt/poky/2.0+snapshot/sysroots/x86_64-pokysdk-linux/usr/share/gc/README.solaris2

[snip]

This was caused by hardcode of datadir.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>