xwayland: add opengl to REQUIRED_DISTRO_FEATURES
* it depends on libepoxy which has this restriction
* fixes:
  ERROR: Nothing PROVIDES 'libepoxy' (but openembedded-core/meta/recipes-graphics/xwayland/xwayland_21.1.1.bb DEPENDS on or otherwise requires it)
  libepoxy was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Nothing RPROVIDES 'xwayland' (but openembedded-core/meta/recipes-graphics/xwayland/xwayland_21.1.1.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'xwayland'
  NOTE: Runtime target 'xwayland' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['xwayland']
  ERROR: Nothing RPROVIDES 'xwayland-dev' (but openembedded-core/meta/recipes-graphics/xwayland/xwayland_21.1.1.bb RDEPENDS on or otherwise requires it)
  No eligible RPROVIDERs exist for 'xwayland-dev'
  NOTE: Runtime target 'xwayland-dev' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['xwayland-dev']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>