lttng-ust: bump PE
The previous lttng-ust had a PE of "1" - that recipe was removed and
replaced with the lttng2-ust recipe, which was renamed back to
lttng-ust.  The new recipe had didn't define a PE so got the default
PE of 0 - this adds the PE back and gives it a value of "2", which
reflects the history and fixes the following error:

ERROR: Package version for package lttng-ust went backwards which
would break package feeds from (1:0.16-r1 to 0:2.1.0-r0)

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>