selftest/files/static-group: add empower group for systemd
When using systemd as INIT_MANAGER and run reproducible selftest,
we'll get the following error:

  ERROR: Nothing PROVIDES 'systemd'
  systemd was skipped: Recipe systemd, package systemd: system
    groupname "empower" does not have a static ID defined. Add
    empower to one of these files: /path/to/build-st/meta-selftest/files/static-group

The 'empower' group was recently introduced in systemd v259. Add it
to files/static-group in meta-selftest layer to aovid the above error.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>