mklibs-native: update broken SRC_URI
fixes checkuri AB failure.

V2] change to snaphot instead of ubuntu

ERROR: mklibs-native-0.1.41-r0 do_checkuri: Fetcher failure for URL: 'http://ftp.de.debian.org/debian/pool/main/m/mklibs/mklibs_0.1.41.tar.xz'. URL http://ftp.de.debian.org/debian/pool/main/m/mklibs/mklibs_0.1.41.tar.xz doesn't work
ERROR: mklibs-native-0.1.41-r0 do_checkuri: Function failed: do_checkuri

[ Yocto #10391]

Signed-off-by: Armin Kuster <akuster@mvista.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>