features_check: improve error message for missing required DISTRO_FEATURES
The original message for REQUIRED_DISTRO_FEATURES entries that were
missing from DISTRO_FEATURES was:

ERROR: Nothing PROVIDES 'core-image-weston'
core-image-weston was skipped: missing required distro feature 'wayland'
(not in DISTRO_FEATURES)

For newcomers, this is error message doesn't provide enough information to
identify the root cause, which could be: using the wrong DISTRO. This patch
changes the error message to include the distro name:

ERROR: Nothing PROVIDES 'core-image-weston'
core-image-weston was skipped: using DISTRO 'nodistro', which is missing
required DISTRO_FEATURES: 'wayland'

Signed-off-by: Walter Werner SCHNEIDER <contact@schnwalter.eu>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>