libuv: upgrade 1.48.0 -> 1.49.0
Changes since version 1.48.0:
==============================
* test: fix -Wpointer-to-int-cast on 32 bits systems
* build: add alias for libuv to CMakeLists.txt
* linux: create io_uring sqpoll ring lazily
* misc: run sample CI when code changes
* linux: fix uv_available_parallelism using cgroup
* doc: fix tty example segfault
* udp,unix: fix sendmsg use-after-free
* cygwin: implement uv_resident_set_memory
* win: almost fix race detecting ESRCH in uv_kill
* test: disable env var test under win32+asan
* unix,fs: fix realpath calls that use the system allocator
* linux: fix /proc/self/stat executable name parsing
* test,ci: fix [AM]San, disable ASLR
* win: remove _alloca usage
* unix: reinstate preadv/pwritev fallback code
* linux: don't delay EPOLL_CTL_DEL operations
* doc: fix typos in ChangeLog
* unix,win: error on zero delay tcp keepalive
* win: simplify uv_once implementation
* doc: correct udp socket options documentation
* linux: don't use sendmmsg() for single datagrams
* unix: fix fd leaks in SCM_RIGHTS error path
* win: robustify uv_os_getenv() error checking
* test: use newer ASSERT_MEM_EQ macro
* unix: de-duplicate conditions for using kqueue
* darwin: simplify uv_hrtime
* mailmap: update saghul's main email address
* win: remove no longer needed define
* doc: fix some typos
* linux,darwin: make `uv_fs_copyfile` behaves like `cp -r`
* dragonfly: disable SO_REUSEPORT for UDP socket bindings
* test: remove the obsolete HAVE_KQUEUE macro
* unix: use the presence of SOCK_* instead of OS macros for socketpair
* bsd: support pipe2() on *BSD
* unix: support SO_REUSEPORT with load balancing for TCP
* doc: add entries for extended getpw
* test: fix the flaky test-tcp-reuseport
* aix,ibmi: fix compilation errors in fs_copyfile
* unix: support SO_REUSEPORT with load balancing for UDP
* tcpkeepalive: distinguish OS versions and use proper time units
* win: map ERROR_BAD_EXE_FORMAT to UV_EFTYPE
* doc: add instruction how to install with Conan
* unix,win: remove unused req parameter from macros
* build: fix android ci build
* unix,win: export wtf8 functions properly
* hurd: add includes and macro prerequisites
* hurd: stub uv_thread_setpriority()
* ci: use macOS 12 for macOS and iOS builds
* darwin: fix crash on iOS(arm64)
* Create dependabot.yml for updating github-actions
* doc: correct names of Win32 APIs in fs.rst
* ci: bump upload and download-artifact versions
* ci: bump actions/setup-python from 4 to 5
* ci: bump KyleMayes/install-llvm-action from 1 to 2
* win,error: remap ERROR_NO_DATA to EAGAIN
* test: handle zero-length udp datagram
* misc: remove splay trees macros
* test,openbsd: remove superfluous ifdef guard
* win,fs: use posix delete semantics, if supported
* win: fix env var in uv_os_homedir and uv_os_tmpdir
* fsevents: detect watched directory removal
* ci: bump actions/checkout to 4
* linux: eliminate a read on eventfd per wakeup
* test: pipe_overlong_path handle ENAMETOOLONG
* win,fs: use the new Windows fast stat API
* win,pipe: fix race with concurrent readers
* win,signal: fix data race dispatching SIGWINCH
* build: ubsan fixes
* linux: disable SQPOLL io_uring by default
* win: fix fs.c ubsan failure
* test: rmdir can return `EEXIST` or `ENOTEMPTY`
* test: check for `UV_CHANGE` or `UV_RENAME` event
* unix,fs: silence -Wunused-result warning
* linux: support abstract unix socket autobinding
* kqueue: use EVFILT_USER for async if available
* win: remove deprecated GetVersionExW call
* doc: document uv_loop_option
* doc: fix the `uv_*_set_data` series of functions
* doc: properly label enumerations and types
* doc: document specific macOS fs_event behavior
* win,pipe: restore fallback handling for blocking pipes
* unix,win: remove unused rb-tree macro parameters
* win: compute parallelism from process cpu affinity
* win: use NtQueryInformationProcess in uv_os_getppid
* win,pipe: fix missing assignment to success
* win: fix uv_available_parallelism on win32
* win,pipe: fix another missing assignment to success
* kqueue: disallow ill-suited file descriptor kinds
* unix: restore tty attributes on handle close
* test: delete test with invalid assumption
* dragonflybsd: fix compilation failure
* test: run android tests on ci
* darwin: add udp mmsg support
* unix: work around arm-linux-gnueabihf-gcc bug
* unix: expand uv_available_parallelism() to support more platforms
* doc: add known issue in armv7

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>