python3-websockets: added python3-zipp as RDEPENDS
Because the Python package 'zipfile' was missing.

root@qemux86-64:~# python3 clTraceback (most recent call last):
  File "/home/root/server.py", line 4, in <module>
    from websockets.server import serve
  File "/usr/lib/python3.12/site-packages/websockets/__init__.py", line 6, in <module>
    from .version import version as __version__  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/version.py", line 3, in <module>
    import importlib.metadata
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 8, in <module>
    import zipfile
ModuleNotFoundError: No module named 'zipfile'

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>